### ISSUE TITLE
Advice for new learners in deep optics.

### ISSUE THREAD

**Issue by JohnleeHIT** [singer-yang/awesome-deep-optics#2]
Hello, this repo is awesome!  I am very interested in this topic.  Is there any advice for a new learner in the field?  I got a bachor's and master's degree on optical engineering, and a PhD in computer science. Thanks!

**Comment by singer-yang** [comment]
Hello, I assume you have enough background in optics. For programming advice, I suggest you start with open-source repos and this book "Computational fourier optics : a MATLAB tutorial." The code link for each paper has been provided after the paper title, if available.

**Comment by JohnleeHIT** [comment]
> 

Thank you for your advice, it means a lot.
